<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="person">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="EmirMujanovic"/>
        <xs:element type="xs:string" name="id12408724"/>
        <xs:element type="xs:string" name="lastcommithash"/>
        <xs:element type="xs:string" name="Emir-Mujanovic"/>
        <xs:element type="xs:string" name="se2-einzelprojekt-service-mujanovic"/>
        <xs:element name="repository" type="xs:string" fixed="https://github.com/Emir-Mujanovic/se2-einzelprojekt-service-mujanovic"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>